SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO AS I JOIN FISH_NAME_INFO AS N
ON I.FISH_TYPE = N.FISH_TYPE
WHERE I.FISH_TYPE IN (
    SELECT FISH_TYPE -- 물고기 종류 별로 가장 큰 물고기 조회
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING LENGTH = MAX(LENGTH)
)
ORDER BY I.ID;
