SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN(
    SELECT T.ITEM_ID -- 희귀도가 'RARE'인 아이템의 부모 아이템 ID
    FROM ITEM_INFO AS I
    JOIN ITEM_TREE AS T
    ON I.ITEM_ID=T.PARENT_ITEM_ID
    WHERE I.RARITY='RARE'
)
ORDER BY ITEM_ID DESC;
